/* Generated by Yosys 0.39+147 (git sha1 0a854cf4c, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

module baud(sys_clk, sys_rst_l, baud_clk);
  wire [23:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire [23:0] _032_;
  wire [23:0] _033_;
  wire [23:0] _034_;
  wire _035_;
  wire [4:0] _036_;
  output baud_clk;
  wire baud_clk;
  wire [23:0] clk_div;
  input sys_clk;
  wire sys_clk;
  input sys_rst_l;
  wire sys_rst_l;
  MUXF7 _037_ (
    .I0(1'h0),
    .I1(1'h0),
    .O(_001_),
    .S(clk_div[10])
  );
  LUT6 #(
    .INIT(64'h0000000000000001)
  ) _038_ (
    .I0(clk_div[1]),
    .I1(clk_div[3]),
    .I2(clk_div[4]),
    .I3(clk_div[5]),
    .I4(clk_div[7]),
    .I5(clk_div[9]),
    .O(_003_)
  );
  MUXF7 _039_ (
    .I0(_003_),
    .I1(1'h0),
    .O(_002_),
    .S(clk_div[10])
  );
  MUXF8 _040_ (
    .I0(_001_),
    .I1(_002_),
    .O(_036_[0]),
    .S(clk_div[8])
  );
  LUT2 #(
    .INIT(4'h1)
  ) _041_ (
    .I0(clk_div[15]),
    .I1(clk_div[16]),
    .O(_036_[1])
  );
  LUT2 #(
    .INIT(4'h1)
  ) _042_ (
    .I0(clk_div[17]),
    .I1(clk_div[18]),
    .O(_036_[2])
  );
  LUT4 #(
    .INIT(16'h0001)
  ) _043_ (
    .I0(clk_div[11]),
    .I1(clk_div[12]),
    .I2(clk_div[13]),
    .I3(clk_div[14]),
    .O(_036_[3])
  );
  MUXF7 _044_ (
    .I0(1'h0),
    .I1(1'h0),
    .O(_004_),
    .S(clk_div[2])
  );
  LUT6 #(
    .INIT(64'h0000000100000000)
  ) _045_ (
    .I0(clk_div[19]),
    .I1(clk_div[20]),
    .I2(clk_div[21]),
    .I3(clk_div[22]),
    .I4(clk_div[23]),
    .I5(clk_div[0]),
    .O(_006_)
  );
  MUXF7 _046_ (
    .I0(1'h0),
    .I1(_006_),
    .O(_005_),
    .S(clk_div[2])
  );
  MUXF8 _047_ (
    .I0(_004_),
    .I1(_005_),
    .O(_036_[4]),
    .S(clk_div[6])
  );
  LUT6 #(
    .INIT(64'h7fffffff00000000)
  ) _048_ (
    .I0(_036_[1]),
    .I1(_036_[2]),
    .I2(_036_[3]),
    .I3(_036_[4]),
    .I4(_036_[0]),
    .I5(_034_[0]),
    .O(_000_[0])
  );
  LUT6 #(
    .INIT(64'h7fffffff00000000)
  ) _049_ (
    .I0(_036_[1]),
    .I1(_036_[2]),
    .I2(_036_[3]),
    .I3(_036_[4]),
    .I4(_036_[0]),
    .I5(_034_[1]),
    .O(_000_[1])
  );
  LUT6 #(
    .INIT(64'h7fffffff00000000)
  ) _050_ (
    .I0(_036_[1]),
    .I1(_036_[2]),
    .I2(_036_[3]),
    .I3(_036_[4]),
    .I4(_036_[0]),
    .I5(_034_[2]),
    .O(_000_[2])
  );
  LUT6 #(
    .INIT(64'h7fffffff00000000)
  ) _051_ (
    .I0(_036_[1]),
    .I1(_036_[2]),
    .I2(_036_[3]),
    .I3(_036_[4]),
    .I4(_036_[0]),
    .I5(_034_[3]),
    .O(_000_[3])
  );
  LUT6 #(
    .INIT(64'h7fffffff00000000)
  ) _052_ (
    .I0(_036_[1]),
    .I1(_036_[2]),
    .I2(_036_[3]),
    .I3(_036_[4]),
    .I4(_036_[0]),
    .I5(_034_[4]),
    .O(_000_[4])
  );
  LUT6 #(
    .INIT(64'h7fffffff00000000)
  ) _053_ (
    .I0(_036_[1]),
    .I1(_036_[2]),
    .I2(_036_[3]),
    .I3(_036_[4]),
    .I4(_036_[0]),
    .I5(_034_[5]),
    .O(_000_[5])
  );
  LUT6 #(
    .INIT(64'h7fffffff00000000)
  ) _054_ (
    .I0(_036_[1]),
    .I1(_036_[2]),
    .I2(_036_[3]),
    .I3(_036_[4]),
    .I4(_036_[0]),
    .I5(_034_[6]),
    .O(_000_[6])
  );
  LUT6 #(
    .INIT(64'h7fffffff00000000)
  ) _055_ (
    .I0(_036_[1]),
    .I1(_036_[2]),
    .I2(_036_[3]),
    .I3(_036_[4]),
    .I4(_036_[0]),
    .I5(_034_[7]),
    .O(_000_[7])
  );
  LUT6 #(
    .INIT(64'h7fffffff00000000)
  ) _056_ (
    .I0(_036_[1]),
    .I1(_036_[2]),
    .I2(_036_[3]),
    .I3(_036_[4]),
    .I4(_036_[0]),
    .I5(_034_[8]),
    .O(_000_[8])
  );
  LUT6 #(
    .INIT(64'h7fffffff00000000)
  ) _057_ (
    .I0(_036_[1]),
    .I1(_036_[2]),
    .I2(_036_[3]),
    .I3(_036_[4]),
    .I4(_036_[0]),
    .I5(_034_[9]),
    .O(_000_[9])
  );
  LUT6 #(
    .INIT(64'h7fffffff00000000)
  ) _058_ (
    .I0(_036_[1]),
    .I1(_036_[2]),
    .I2(_036_[3]),
    .I3(_036_[4]),
    .I4(_036_[0]),
    .I5(_034_[10]),
    .O(_000_[10])
  );
  LUT6 #(
    .INIT(64'h7fffffff00000000)
  ) _059_ (
    .I0(_036_[1]),
    .I1(_036_[2]),
    .I2(_036_[3]),
    .I3(_036_[4]),
    .I4(_036_[0]),
    .I5(_034_[11]),
    .O(_000_[11])
  );
  LUT6 #(
    .INIT(64'h7fffffff00000000)
  ) _060_ (
    .I0(_036_[1]),
    .I1(_036_[2]),
    .I2(_036_[3]),
    .I3(_036_[4]),
    .I4(_036_[0]),
    .I5(_034_[12]),
    .O(_000_[12])
  );
  LUT6 #(
    .INIT(64'h7fffffff00000000)
  ) _061_ (
    .I0(_036_[1]),
    .I1(_036_[2]),
    .I2(_036_[3]),
    .I3(_036_[4]),
    .I4(_036_[0]),
    .I5(_034_[13]),
    .O(_000_[13])
  );
  LUT6 #(
    .INIT(64'h7fffffff00000000)
  ) _062_ (
    .I0(_036_[1]),
    .I1(_036_[2]),
    .I2(_036_[3]),
    .I3(_036_[4]),
    .I4(_036_[0]),
    .I5(_034_[14]),
    .O(_000_[14])
  );
  LUT6 #(
    .INIT(64'h7fffffff00000000)
  ) _063_ (
    .I0(_036_[1]),
    .I1(_036_[2]),
    .I2(_036_[3]),
    .I3(_036_[4]),
    .I4(_036_[0]),
    .I5(_034_[15]),
    .O(_000_[15])
  );
  LUT6 #(
    .INIT(64'h7fffffff00000000)
  ) _064_ (
    .I0(_036_[1]),
    .I1(_036_[2]),
    .I2(_036_[3]),
    .I3(_036_[4]),
    .I4(_036_[0]),
    .I5(_034_[16]),
    .O(_000_[16])
  );
  LUT6 #(
    .INIT(64'h7fffffff00000000)
  ) _065_ (
    .I0(_036_[1]),
    .I1(_036_[2]),
    .I2(_036_[3]),
    .I3(_036_[4]),
    .I4(_036_[0]),
    .I5(_034_[17]),
    .O(_000_[17])
  );
  LUT6 #(
    .INIT(64'h7fffffff00000000)
  ) _066_ (
    .I0(_036_[1]),
    .I1(_036_[2]),
    .I2(_036_[3]),
    .I3(_036_[4]),
    .I4(_036_[0]),
    .I5(_034_[18]),
    .O(_000_[18])
  );
  LUT6 #(
    .INIT(64'h7fffffff00000000)
  ) _067_ (
    .I0(_036_[1]),
    .I1(_036_[2]),
    .I2(_036_[3]),
    .I3(_036_[4]),
    .I4(_036_[0]),
    .I5(_034_[19]),
    .O(_000_[19])
  );
  LUT6 #(
    .INIT(64'h7fffffff00000000)
  ) _068_ (
    .I0(_036_[1]),
    .I1(_036_[2]),
    .I2(_036_[3]),
    .I3(_036_[4]),
    .I4(_036_[0]),
    .I5(_034_[20]),
    .O(_000_[20])
  );
  LUT6 #(
    .INIT(64'h7fffffff00000000)
  ) _069_ (
    .I0(_036_[1]),
    .I1(_036_[2]),
    .I2(_036_[3]),
    .I3(_036_[4]),
    .I4(_036_[0]),
    .I5(_034_[21]),
    .O(_000_[21])
  );
  LUT6 #(
    .INIT(64'h7fffffff00000000)
  ) _070_ (
    .I0(_036_[1]),
    .I1(_036_[2]),
    .I2(_036_[3]),
    .I3(_036_[4]),
    .I4(_036_[0]),
    .I5(_034_[22]),
    .O(_000_[22])
  );
  LUT6 #(
    .INIT(64'h7fffffff00000000)
  ) _071_ (
    .I0(_036_[1]),
    .I1(_036_[2]),
    .I2(_036_[3]),
    .I3(_036_[4]),
    .I4(_036_[0]),
    .I5(_034_[23]),
    .O(_000_[23])
  );
  INV _072_ (
    .I(sys_rst_l),
    .O(_007_)
  );
  INV _073_ (
    .I(clk_div[0]),
    .O(_033_[0])
  );
  INV _074_ (
    .I(sys_rst_l),
    .O(_008_)
  );
  INV _075_ (
    .I(sys_rst_l),
    .O(_009_)
  );
  INV _076_ (
    .I(sys_rst_l),
    .O(_010_)
  );
  INV _077_ (
    .I(sys_rst_l),
    .O(_011_)
  );
  INV _078_ (
    .I(sys_rst_l),
    .O(_012_)
  );
  INV _079_ (
    .I(sys_rst_l),
    .O(_013_)
  );
  INV _080_ (
    .I(sys_rst_l),
    .O(_014_)
  );
  INV _081_ (
    .I(sys_rst_l),
    .O(_015_)
  );
  INV _082_ (
    .I(sys_rst_l),
    .O(_016_)
  );
  INV _083_ (
    .I(sys_rst_l),
    .O(_017_)
  );
  INV _084_ (
    .I(sys_rst_l),
    .O(_018_)
  );
  INV _085_ (
    .I(sys_rst_l),
    .O(_019_)
  );
  INV _086_ (
    .I(sys_rst_l),
    .O(_020_)
  );
  INV _087_ (
    .I(sys_rst_l),
    .O(_021_)
  );
  INV _088_ (
    .I(sys_rst_l),
    .O(_022_)
  );
  INV _089_ (
    .I(sys_rst_l),
    .O(_023_)
  );
  INV _090_ (
    .I(sys_rst_l),
    .O(_024_)
  );
  INV _091_ (
    .I(sys_rst_l),
    .O(_025_)
  );
  INV _092_ (
    .I(sys_rst_l),
    .O(_026_)
  );
  INV _093_ (
    .I(sys_rst_l),
    .O(_027_)
  );
  INV _094_ (
    .I(sys_rst_l),
    .O(_028_)
  );
  INV _095_ (
    .I(sys_rst_l),
    .O(_029_)
  );
  INV _096_ (
    .I(sys_rst_l),
    .O(_030_)
  );
  INV _097_ (
    .I(sys_rst_l),
    .O(_031_)
  );
  CARRY4 _098_ (
    .CI(1'h0),
    .CO(_032_[3:0]),
    .CYINIT(1'h0),
    .DI(4'h1),
    .O(_034_[3:0]),
    .S({ clk_div[3:1], _033_[0] })
  );
  CARRY4 _099_ (
    .CI(_032_[3]),
    .CO(_032_[7:4]),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O(_034_[7:4]),
    .S(clk_div[7:4])
  );
  CARRY4 _100_ (
    .CI(_032_[7]),
    .CO(_032_[11:8]),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O(_034_[11:8]),
    .S(clk_div[11:8])
  );
  CARRY4 _101_ (
    .CI(_032_[11]),
    .CO(_032_[15:12]),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O(_034_[15:12]),
    .S(clk_div[15:12])
  );
  CARRY4 _102_ (
    .CI(_032_[15]),
    .CO(_032_[19:16]),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O(_034_[19:16]),
    .S(clk_div[19:16])
  );
  CARRY4 _103_ (
    .CI(_032_[19]),
    .CO(_032_[23:20]),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O(_034_[23:20]),
    .S(clk_div[23:20])
  );
  FDCE #(
    .INIT(1'hx)
  ) _104_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_007_),
    .D(_035_),
    .Q(baud_clk)
  );
  FDCE #(
    .INIT(1'hx)
  ) _105_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_008_),
    .D(_000_[0]),
    .Q(clk_div[0])
  );
  FDCE #(
    .INIT(1'hx)
  ) _106_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_009_),
    .D(_000_[1]),
    .Q(clk_div[1])
  );
  FDCE #(
    .INIT(1'hx)
  ) _107_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_010_),
    .D(_000_[2]),
    .Q(clk_div[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _108_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_011_),
    .D(_000_[3]),
    .Q(clk_div[3])
  );
  FDCE #(
    .INIT(1'hx)
  ) _109_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_012_),
    .D(_000_[4]),
    .Q(clk_div[4])
  );
  FDCE #(
    .INIT(1'hx)
  ) _110_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_013_),
    .D(_000_[5]),
    .Q(clk_div[5])
  );
  FDCE #(
    .INIT(1'hx)
  ) _111_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_014_),
    .D(_000_[6]),
    .Q(clk_div[6])
  );
  FDCE #(
    .INIT(1'hx)
  ) _112_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_015_),
    .D(_000_[7]),
    .Q(clk_div[7])
  );
  FDCE #(
    .INIT(1'hx)
  ) _113_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_016_),
    .D(_000_[8]),
    .Q(clk_div[8])
  );
  FDCE #(
    .INIT(1'hx)
  ) _114_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_017_),
    .D(_000_[9]),
    .Q(clk_div[9])
  );
  FDCE #(
    .INIT(1'hx)
  ) _115_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_018_),
    .D(_000_[10]),
    .Q(clk_div[10])
  );
  FDCE #(
    .INIT(1'hx)
  ) _116_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_019_),
    .D(_000_[11]),
    .Q(clk_div[11])
  );
  FDCE #(
    .INIT(1'hx)
  ) _117_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_020_),
    .D(_000_[12]),
    .Q(clk_div[12])
  );
  FDCE #(
    .INIT(1'hx)
  ) _118_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_021_),
    .D(_000_[13]),
    .Q(clk_div[13])
  );
  FDCE #(
    .INIT(1'hx)
  ) _119_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_022_),
    .D(_000_[14]),
    .Q(clk_div[14])
  );
  FDCE #(
    .INIT(1'hx)
  ) _120_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_023_),
    .D(_000_[15]),
    .Q(clk_div[15])
  );
  FDCE #(
    .INIT(1'hx)
  ) _121_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_024_),
    .D(_000_[16]),
    .Q(clk_div[16])
  );
  FDCE #(
    .INIT(1'hx)
  ) _122_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_025_),
    .D(_000_[17]),
    .Q(clk_div[17])
  );
  FDCE #(
    .INIT(1'hx)
  ) _123_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_026_),
    .D(_000_[18]),
    .Q(clk_div[18])
  );
  FDCE #(
    .INIT(1'hx)
  ) _124_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_027_),
    .D(_000_[19]),
    .Q(clk_div[19])
  );
  FDCE #(
    .INIT(1'hx)
  ) _125_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_028_),
    .D(_000_[20]),
    .Q(clk_div[20])
  );
  FDCE #(
    .INIT(1'hx)
  ) _126_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_029_),
    .D(_000_[21]),
    .Q(clk_div[21])
  );
  FDCE #(
    .INIT(1'hx)
  ) _127_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_030_),
    .D(_000_[22]),
    .Q(clk_div[22])
  );
  FDCE #(
    .INIT(1'hx)
  ) _128_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_031_),
    .D(_000_[23]),
    .Q(clk_div[23])
  );
  LUT6 #(
    .INIT(64'h7fffffff80000000)
  ) _129_ (
    .I0(_036_[4]),
    .I1(_036_[3]),
    .I2(_036_[2]),
    .I3(_036_[1]),
    .I4(_036_[0]),
    .I5(baud_clk),
    .O(_035_)
  );
  assign _033_[23:1] = clk_div[23:1];
endmodule

module u_rec(sys_rst_l, sys_clk, uart_dataH, rec_dataH, rec_readyH);
  wire [3:0] _00_;
  wire [3:0] _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire [3:0] _25_;
  wire [3:0] _26_;
  wire [3:0] _27_;
  wire [3:0] _28_;
  wire [3:0] _29_;
  wire [3:0] _30_;
  wire [5:0] _31_;
  wire [5:0] _32_;
  wire [1:0] _33_;
  wire [3:0] bitCell_cntrH;
  wire [2:0] next_state;
  wire [7:0] par_dataH;
  wire rec_datH;
  wire rec_datSyncH;
  output [7:0] rec_dataH;
  wire [7:0] rec_dataH;
  output rec_readyH;
  wire rec_readyH;
  wire rec_readyInH;
  wire [3:0] recd_bitCntrH;
  wire [2:0] state;
  input sys_clk;
  wire sys_clk;
  input sys_rst_l;
  wire sys_rst_l;
  input uart_dataH;
  wire uart_dataH;
  LUT3 #(
    .INIT(8'hc5)
  ) _34_ (
    .I0(state[0]),
    .I1(state[2]),
    .I2(state[1]),
    .O(_33_[0])
  );
  LUT4 #(
    .INIT(16'hf03b)
  ) _35_ (
    .I0(rec_datH),
    .I1(state[0]),
    .I2(state[2]),
    .I3(state[1]),
    .O(_02_)
  );
  LUT2 #(
    .INIT(4'h8)
  ) _36_ (
    .I0(_33_[0]),
    .I1(_27_[0]),
    .O(_01_[0])
  );
  LUT2 #(
    .INIT(4'h8)
  ) _37_ (
    .I0(_33_[0]),
    .I1(_27_[1]),
    .O(_01_[1])
  );
  LUT2 #(
    .INIT(4'h8)
  ) _38_ (
    .I0(_33_[0]),
    .I1(_27_[2]),
    .O(_01_[2])
  );
  LUT2 #(
    .INIT(4'h8)
  ) _39_ (
    .I0(_33_[0]),
    .I1(_27_[3]),
    .O(_01_[3])
  );
  LUT6 #(
    .INIT(64'h3030503300000000)
  ) _40_ (
    .I0(_31_[1]),
    .I1(_31_[0]),
    .I2(state[1]),
    .I3(state[0]),
    .I4(state[2]),
    .I5(_30_[0]),
    .O(_00_[0])
  );
  LUT4 #(
    .INIT(16'h0100)
  ) _41_ (
    .I0(bitCell_cntrH[3]),
    .I1(bitCell_cntrH[0]),
    .I2(bitCell_cntrH[1]),
    .I3(bitCell_cntrH[2]),
    .O(_31_[0])
  );
  LUT4 #(
    .INIT(16'h4000)
  ) _42_ (
    .I0(bitCell_cntrH[0]),
    .I1(bitCell_cntrH[3]),
    .I2(bitCell_cntrH[1]),
    .I3(bitCell_cntrH[2]),
    .O(_31_[1])
  );
  LUT6 #(
    .INIT(64'h3030503300000000)
  ) _43_ (
    .I0(_31_[1]),
    .I1(_31_[0]),
    .I2(state[1]),
    .I3(state[0]),
    .I4(state[2]),
    .I5(_30_[1]),
    .O(_00_[1])
  );
  LUT6 #(
    .INIT(64'h3030503300000000)
  ) _44_ (
    .I0(_31_[1]),
    .I1(_31_[0]),
    .I2(state[1]),
    .I3(state[0]),
    .I4(state[2]),
    .I5(_30_[2]),
    .O(_00_[2])
  );
  LUT6 #(
    .INIT(64'h3030503300000000)
  ) _45_ (
    .I0(_31_[1]),
    .I1(_31_[0]),
    .I2(state[1]),
    .I3(state[0]),
    .I4(state[2]),
    .I5(_30_[3]),
    .O(_00_[3])
  );
  LUT6 #(
    .INIT(64'hffff50c0ffffffff)
  ) _46_ (
    .I0(_31_[1]),
    .I1(_31_[0]),
    .I2(state[1]),
    .I3(state[0]),
    .I4(_32_[4]),
    .I5(_32_[5]),
    .O(next_state[0])
  );
  LUT3 #(
    .INIT(8'h0d)
  ) _47_ (
    .I0(rec_datH),
    .I1(state[1]),
    .I2(state[2]),
    .O(_32_[5])
  );
  LUT6 #(
    .INIT(64'h0100000000000000)
  ) _48_ (
    .I0(recd_bitCntrH[0]),
    .I1(recd_bitCntrH[1]),
    .I2(recd_bitCntrH[2]),
    .I3(state[1]),
    .I4(recd_bitCntrH[3]),
    .I5(state[0]),
    .O(_32_[4])
  );
  LUT6 #(
    .INIT(64'h0000ffff303f50ff)
  ) _49_ (
    .I0(_31_[0]),
    .I1(_31_[1]),
    .I2(state[1]),
    .I3(rec_datH),
    .I4(state[0]),
    .I5(state[2]),
    .O(next_state[1])
  );
  LUT4 #(
    .INIT(16'h4000)
  ) _50_ (
    .I0(state[2]),
    .I1(_31_[1]),
    .I2(state[1]),
    .I3(state[0]),
    .O(next_state[2])
  );
  LUT4 #(
    .INIT(16'hca0c)
  ) _51_ (
    .I0(state[0]),
    .I1(rec_datH),
    .I2(state[1]),
    .I3(state[2]),
    .O(rec_readyInH)
  );
  INV _52_ (
    .I(sys_rst_l),
    .O(_03_)
  );
  INV _53_ (
    .I(recd_bitCntrH[0]),
    .O(_26_[0])
  );
  INV _54_ (
    .I(bitCell_cntrH[0]),
    .O(_29_[0])
  );
  INV _55_ (
    .I(sys_rst_l),
    .O(_04_)
  );
  INV _56_ (
    .I(sys_rst_l),
    .O(_05_)
  );
  INV _57_ (
    .I(sys_rst_l),
    .O(_06_)
  );
  INV _58_ (
    .I(sys_rst_l),
    .O(_07_)
  );
  INV _59_ (
    .I(sys_rst_l),
    .O(_08_)
  );
  INV _60_ (
    .I(sys_rst_l),
    .O(_09_)
  );
  INV _61_ (
    .I(sys_rst_l),
    .O(_10_)
  );
  INV _62_ (
    .I(sys_rst_l),
    .O(_11_)
  );
  INV _63_ (
    .I(sys_rst_l),
    .O(_12_)
  );
  INV _64_ (
    .I(sys_rst_l),
    .O(_13_)
  );
  INV _65_ (
    .I(sys_rst_l),
    .O(_14_)
  );
  INV _66_ (
    .I(sys_rst_l),
    .O(_15_)
  );
  INV _67_ (
    .I(sys_rst_l),
    .O(_16_)
  );
  INV _68_ (
    .I(sys_rst_l),
    .O(_17_)
  );
  INV _69_ (
    .I(sys_rst_l),
    .O(_18_)
  );
  INV _70_ (
    .I(sys_rst_l),
    .O(_19_)
  );
  INV _71_ (
    .I(sys_rst_l),
    .O(_20_)
  );
  INV _72_ (
    .I(sys_rst_l),
    .O(_21_)
  );
  INV _73_ (
    .I(sys_rst_l),
    .O(_22_)
  );
  INV _74_ (
    .I(sys_rst_l),
    .O(_23_)
  );
  INV _75_ (
    .I(sys_rst_l),
    .O(_24_)
  );
  CARRY4 _76_ (
    .CI(1'h0),
    .CO(_25_),
    .CYINIT(1'h0),
    .DI(4'h1),
    .O(_27_),
    .S({ recd_bitCntrH[3:1], _26_[0] })
  );
  CARRY4 _77_ (
    .CI(1'h0),
    .CO(_28_),
    .CYINIT(1'h0),
    .DI(4'h1),
    .O(_30_),
    .S({ bitCell_cntrH[3:1], _29_[0] })
  );
  FDCE #(
    .INIT(1'hx)
  ) _78_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_03_),
    .D(rec_readyInH),
    .Q(rec_readyH)
  );
  FDPE #(
    .INIT(1'hx)
  ) _79_ (
    .C(sys_clk),
    .CE(1'h1),
    .D(next_state[0]),
    .PRE(_04_),
    .Q(state[0])
  );
  FDCE #(
    .INIT(1'hx)
  ) _80_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_05_),
    .D(next_state[1]),
    .Q(state[1])
  );
  FDCE #(
    .INIT(1'hx)
  ) _81_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_06_),
    .D(next_state[2]),
    .Q(state[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _82_ (
    .C(sys_clk),
    .CE(_02_),
    .CLR(_07_),
    .D(_01_[0]),
    .Q(recd_bitCntrH[0])
  );
  FDCE #(
    .INIT(1'hx)
  ) _83_ (
    .C(sys_clk),
    .CE(_02_),
    .CLR(_08_),
    .D(_01_[1]),
    .Q(recd_bitCntrH[1])
  );
  FDCE #(
    .INIT(1'hx)
  ) _84_ (
    .C(sys_clk),
    .CE(_02_),
    .CLR(_09_),
    .D(_01_[2]),
    .Q(recd_bitCntrH[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _85_ (
    .C(sys_clk),
    .CE(_02_),
    .CLR(_10_),
    .D(_01_[3]),
    .Q(recd_bitCntrH[3])
  );
  FDCE #(
    .INIT(1'hx)
  ) _86_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_11_),
    .D(_00_[0]),
    .Q(bitCell_cntrH[0])
  );
  FDCE #(
    .INIT(1'hx)
  ) _87_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_12_),
    .D(_00_[1]),
    .Q(bitCell_cntrH[1])
  );
  FDCE #(
    .INIT(1'hx)
  ) _88_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_13_),
    .D(_00_[2]),
    .Q(bitCell_cntrH[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _89_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_14_),
    .D(_00_[3]),
    .Q(bitCell_cntrH[3])
  );
  FDPE #(
    .INIT(1'hx)
  ) _90_ (
    .C(sys_clk),
    .CE(1'h1),
    .D(rec_datSyncH),
    .PRE(_15_),
    .Q(rec_datH)
  );
  FDPE #(
    .INIT(1'hx)
  ) _91_ (
    .C(sys_clk),
    .CE(1'h1),
    .D(uart_dataH),
    .PRE(_16_),
    .Q(rec_datSyncH)
  );
  FDCE #(
    .INIT(1'hx)
  ) _92_ (
    .C(sys_clk),
    .CE(_33_[0]),
    .CLR(_17_),
    .D(par_dataH[1]),
    .Q(par_dataH[0])
  );
  FDCE #(
    .INIT(1'hx)
  ) _93_ (
    .C(sys_clk),
    .CE(_33_[0]),
    .CLR(_18_),
    .D(par_dataH[2]),
    .Q(par_dataH[1])
  );
  FDCE #(
    .INIT(1'hx)
  ) _94_ (
    .C(sys_clk),
    .CE(_33_[0]),
    .CLR(_19_),
    .D(par_dataH[3]),
    .Q(par_dataH[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _95_ (
    .C(sys_clk),
    .CE(_33_[0]),
    .CLR(_20_),
    .D(par_dataH[4]),
    .Q(par_dataH[3])
  );
  FDCE #(
    .INIT(1'hx)
  ) _96_ (
    .C(sys_clk),
    .CE(_33_[0]),
    .CLR(_21_),
    .D(par_dataH[5]),
    .Q(par_dataH[4])
  );
  FDCE #(
    .INIT(1'hx)
  ) _97_ (
    .C(sys_clk),
    .CE(_33_[0]),
    .CLR(_22_),
    .D(par_dataH[6]),
    .Q(par_dataH[5])
  );
  FDCE #(
    .INIT(1'hx)
  ) _98_ (
    .C(sys_clk),
    .CE(_33_[0]),
    .CLR(_23_),
    .D(par_dataH[7]),
    .Q(par_dataH[6])
  );
  FDCE #(
    .INIT(1'hx)
  ) _99_ (
    .C(sys_clk),
    .CE(_33_[0]),
    .CLR(_24_),
    .D(rec_datH),
    .Q(par_dataH[7])
  );
  assign _32_[3:0] = { state[0], state[1], _31_[0], _31_[1] };
  assign _31_[5:2] = { state[2], state[0], rec_datH, state[1] };
  assign _33_[1] = _27_[2];
  assign _26_[3:1] = recd_bitCntrH[3:1];
  assign _29_[3:1] = bitCell_cntrH[3:1];
  assign rec_dataH = par_dataH;
endmodule

module u_xmit(sys_clk, sys_rst_l, uart_xmitH, xmitH, xmit_dataH, xmit_doneH);
  wire [4:0] _000_;
  wire [3:0] _001_;
  wire [7:0] _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire [4:0] _032_;
  wire [4:0] _033_;
  wire [4:0] _034_;
  wire [7:0] _035_;
  wire [7:0] _036_;
  wire [3:0] _037_;
  wire [3:0] _038_;
  wire [3:0] _039_;
  wire _040_;
  wire [1:0] _041_;
  wire [5:0] _042_;
  wire [1:0] _043_;
  wire [4:0] bitCell_cntrH;
  wire [3:0] bitCountH;
  wire [2:0] next_state;
  wire [2:0] state;
  input sys_clk;
  wire sys_clk;
  input sys_rst_l;
  wire sys_rst_l;
  output uart_xmitH;
  wire uart_xmitH;
  input xmitH;
  wire xmitH;
  wire [7:0] xmit_ShiftRegH;
  input [7:0] xmit_dataH;
  wire [7:0] xmit_dataH;
  output xmit_doneH;
  wire xmit_doneH;
  wire xmit_doneInH;
  LUT4 #(
    .INIT(16'hcf32)
  ) _044_ (
    .I0(xmitH),
    .I1(state[1]),
    .I2(state[0]),
    .I3(state[2]),
    .O(_009_)
  );
  LUT6 #(
    .INIT(64'h3f3300000a003b33)
  ) _045_ (
    .I0(state[0]),
    .I1(xmitH),
    .I2(_042_[0]),
    .I3(_042_[1]),
    .I4(state[1]),
    .I5(state[2]),
    .O(_010_)
  );
  LUT5 #(
    .INIT(32'd268435456)
  ) _046_ (
    .I0(bitCell_cntrH[4]),
    .I1(bitCell_cntrH[0]),
    .I2(bitCell_cntrH[1]),
    .I3(bitCell_cntrH[2]),
    .I4(bitCell_cntrH[3]),
    .O(_042_[1])
  );
  LUT4 #(
    .INIT(16'h0100)
  ) _047_ (
    .I0(bitCountH[0]),
    .I1(bitCountH[1]),
    .I2(bitCountH[2]),
    .I3(bitCountH[3]),
    .O(_042_[0])
  );
  LUT2 #(
    .INIT(4'h4)
  ) _048_ (
    .I0(_043_[0]),
    .I1(_039_[0]),
    .O(_001_[0])
  );
  LUT3 #(
    .INIT(8'h41)
  ) _049_ (
    .I0(xmitH),
    .I1(state[2]),
    .I2(state[1]),
    .O(_043_[0])
  );
  LUT2 #(
    .INIT(4'h4)
  ) _050_ (
    .I0(_043_[0]),
    .I1(_039_[1]),
    .O(_001_[1])
  );
  LUT2 #(
    .INIT(4'h4)
  ) _051_ (
    .I0(_043_[0]),
    .I1(_039_[2]),
    .O(_001_[2])
  );
  LUT2 #(
    .INIT(4'h4)
  ) _052_ (
    .I0(_043_[0]),
    .I1(_039_[3]),
    .O(_001_[3])
  );
  LUT5 #(
    .INIT(32'd2899102892)
  ) _053_ (
    .I0(xmit_dataH[0]),
    .I1(xmit_ShiftRegH[1]),
    .I2(xmitH),
    .I3(state[1]),
    .I4(state[2]),
    .O(_002_[0])
  );
  LUT5 #(
    .INIT(32'd2899102892)
  ) _054_ (
    .I0(xmit_dataH[1]),
    .I1(xmit_ShiftRegH[2]),
    .I2(xmitH),
    .I3(state[1]),
    .I4(state[2]),
    .O(_002_[1])
  );
  LUT5 #(
    .INIT(32'd2899102892)
  ) _055_ (
    .I0(xmit_dataH[2]),
    .I1(xmit_ShiftRegH[3]),
    .I2(xmitH),
    .I3(state[1]),
    .I4(state[2]),
    .O(_002_[2])
  );
  LUT5 #(
    .INIT(32'd2899102892)
  ) _056_ (
    .I0(xmit_dataH[3]),
    .I1(xmit_ShiftRegH[4]),
    .I2(xmitH),
    .I3(state[1]),
    .I4(state[2]),
    .O(_002_[3])
  );
  LUT5 #(
    .INIT(32'd2899102892)
  ) _057_ (
    .I0(xmit_dataH[4]),
    .I1(xmit_ShiftRegH[5]),
    .I2(xmitH),
    .I3(state[1]),
    .I4(state[2]),
    .O(_002_[4])
  );
  LUT5 #(
    .INIT(32'd2899102892)
  ) _058_ (
    .I0(xmit_dataH[5]),
    .I1(xmit_ShiftRegH[6]),
    .I2(xmitH),
    .I3(state[1]),
    .I4(state[2]),
    .O(_002_[5])
  );
  LUT5 #(
    .INIT(32'd2899102892)
  ) _059_ (
    .I0(xmit_dataH[6]),
    .I1(xmit_ShiftRegH[7]),
    .I2(xmitH),
    .I3(state[1]),
    .I4(state[2]),
    .O(_002_[6])
  );
  LUT2 #(
    .INIT(4'h4)
  ) _060_ (
    .I0(_041_[0]),
    .I1(_034_[0]),
    .O(_000_[0])
  );
  LUT2 #(
    .INIT(4'h1)
  ) _061_ (
    .I0(state[1]),
    .I1(state[0]),
    .O(_005_)
  );
  LUT2 #(
    .INIT(4'h1)
  ) _062_ (
    .I0(state[1]),
    .I1(state[0]),
    .O(_006_)
  );
  MUXF7 _063_ (
    .I0(_005_),
    .I1(_006_),
    .O(_003_),
    .S(bitCell_cntrH[2])
  );
  LUT2 #(
    .INIT(4'h1)
  ) _064_ (
    .I0(state[1]),
    .I1(state[0]),
    .O(_007_)
  );
  LUT6 #(
    .INIT(64'h040b575d00005555)
  ) _065_ (
    .I0(state[1]),
    .I1(state[2]),
    .I2(bitCell_cntrH[4]),
    .I3(bitCell_cntrH[0]),
    .I4(state[0]),
    .I5(bitCell_cntrH[1]),
    .O(_008_)
  );
  MUXF7 _066_ (
    .I0(_007_),
    .I1(_008_),
    .O(_004_),
    .S(bitCell_cntrH[2])
  );
  MUXF8 _067_ (
    .I0(_003_),
    .I1(_004_),
    .O(_041_[0]),
    .S(bitCell_cntrH[3])
  );
  LUT2 #(
    .INIT(4'h4)
  ) _068_ (
    .I0(_041_[0]),
    .I1(_034_[1]),
    .O(_000_[1])
  );
  LUT2 #(
    .INIT(4'h4)
  ) _069_ (
    .I0(_041_[0]),
    .I1(_034_[2]),
    .O(_000_[2])
  );
  LUT2 #(
    .INIT(4'h4)
  ) _070_ (
    .I0(_041_[0]),
    .I1(_034_[3]),
    .O(_000_[3])
  );
  LUT2 #(
    .INIT(4'h4)
  ) _071_ (
    .I0(_041_[0]),
    .I1(_034_[4]),
    .O(_000_[4])
  );
  LUT6 #(
    .INIT(64'h00ffffffb0b0f000)
  ) _072_ (
    .I0(_042_[0]),
    .I1(_042_[1]),
    .I2(state[1]),
    .I3(_042_[3]),
    .I4(state[0]),
    .I5(state[2]),
    .O(next_state[0])
  );
  LUT5 #(
    .INIT(32'd1073741824)
  ) _073_ (
    .I0(bitCell_cntrH[4]),
    .I1(bitCell_cntrH[0]),
    .I2(bitCell_cntrH[1]),
    .I3(bitCell_cntrH[2]),
    .I4(bitCell_cntrH[3]),
    .O(_042_[3])
  );
  LUT5 #(
    .INIT(32'd255791018)
  ) _074_ (
    .I0(xmitH),
    .I1(_042_[1]),
    .I2(state[0]),
    .I3(state[2]),
    .I4(state[1]),
    .O(next_state[1])
  );
  LUT5 #(
    .INIT(32'd16252928)
  ) _075_ (
    .I0(state[1]),
    .I1(_042_[1]),
    .I2(state[2]),
    .I3(_042_[3]),
    .I4(state[0]),
    .O(next_state[2])
  );
  LUT5 #(
    .INIT(32'd260571151)
  ) _076_ (
    .I0(_042_[3]),
    .I1(state[0]),
    .I2(xmitH),
    .I3(state[1]),
    .I4(state[2]),
    .O(xmit_doneInH)
  );
  LUT4 #(
    .INIT(16'h2c0b)
  ) _077_ (
    .I0(xmit_ShiftRegH[0]),
    .I1(state[2]),
    .I2(state[1]),
    .I3(state[0]),
    .O(uart_xmitH)
  );
  INV _078_ (
    .I(sys_rst_l),
    .O(_011_)
  );
  INV _079_ (
    .I(bitCountH[0]),
    .O(_038_[0])
  );
  INV _080_ (
    .I(bitCell_cntrH[0]),
    .O(_033_[0])
  );
  INV _081_ (
    .I(sys_rst_l),
    .O(_012_)
  );
  INV _082_ (
    .I(sys_rst_l),
    .O(_013_)
  );
  INV _083_ (
    .I(sys_rst_l),
    .O(_014_)
  );
  INV _084_ (
    .I(sys_rst_l),
    .O(_015_)
  );
  INV _085_ (
    .I(sys_rst_l),
    .O(_016_)
  );
  INV _086_ (
    .I(sys_rst_l),
    .O(_017_)
  );
  INV _087_ (
    .I(sys_rst_l),
    .O(_018_)
  );
  INV _088_ (
    .I(sys_rst_l),
    .O(_019_)
  );
  INV _089_ (
    .I(sys_rst_l),
    .O(_020_)
  );
  INV _090_ (
    .I(sys_rst_l),
    .O(_021_)
  );
  INV _091_ (
    .I(sys_rst_l),
    .O(_022_)
  );
  INV _092_ (
    .I(sys_rst_l),
    .O(_023_)
  );
  INV _093_ (
    .I(sys_rst_l),
    .O(_024_)
  );
  INV _094_ (
    .I(sys_rst_l),
    .O(_025_)
  );
  INV _095_ (
    .I(sys_rst_l),
    .O(_026_)
  );
  INV _096_ (
    .I(sys_rst_l),
    .O(_027_)
  );
  INV _097_ (
    .I(sys_rst_l),
    .O(_028_)
  );
  INV _098_ (
    .I(sys_rst_l),
    .O(_029_)
  );
  INV _099_ (
    .I(sys_rst_l),
    .O(_030_)
  );
  INV _100_ (
    .I(sys_rst_l),
    .O(_031_)
  );
  CARRY4 _101_ (
    .CI(1'h0),
    .CO(_032_[3:0]),
    .CYINIT(1'h0),
    .DI(4'h1),
    .O(_034_[3:0]),
    .S({ bitCell_cntrH[3:1], _033_[0] })
  );
  CARRY4 _102_ (
    .CI(_032_[3]),
    .CO({ _035_[7:5], _032_[4] }),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O({ _036_[7:5], _034_[4] }),
    .S({ 3'h0, bitCell_cntrH[4] })
  );
  CARRY4 _103_ (
    .CI(1'h0),
    .CO(_037_),
    .CYINIT(1'h0),
    .DI(4'h1),
    .O(_039_),
    .S({ bitCountH[3:1], _038_[0] })
  );
  FDCE #(
    .INIT(1'hx)
  ) _104_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_011_),
    .D(xmit_doneInH),
    .Q(xmit_doneH)
  );
  FDCE #(
    .INIT(1'hx)
  ) _105_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_012_),
    .D(next_state[0]),
    .Q(state[0])
  );
  FDCE #(
    .INIT(1'hx)
  ) _106_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_013_),
    .D(next_state[1]),
    .Q(state[1])
  );
  FDCE #(
    .INIT(1'hx)
  ) _107_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_014_),
    .D(next_state[2]),
    .Q(state[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _108_ (
    .C(sys_clk),
    .CE(_010_),
    .CLR(_015_),
    .D(_001_[0]),
    .Q(bitCountH[0])
  );
  FDCE #(
    .INIT(1'hx)
  ) _109_ (
    .C(sys_clk),
    .CE(_010_),
    .CLR(_016_),
    .D(_001_[1]),
    .Q(bitCountH[1])
  );
  FDCE #(
    .INIT(1'hx)
  ) _110_ (
    .C(sys_clk),
    .CE(_010_),
    .CLR(_017_),
    .D(_001_[2]),
    .Q(bitCountH[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _111_ (
    .C(sys_clk),
    .CE(_010_),
    .CLR(_018_),
    .D(_001_[3]),
    .Q(bitCountH[3])
  );
  FDCE #(
    .INIT(1'hx)
  ) _112_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_019_),
    .D(_000_[0]),
    .Q(bitCell_cntrH[0])
  );
  FDCE #(
    .INIT(1'hx)
  ) _113_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_020_),
    .D(_000_[1]),
    .Q(bitCell_cntrH[1])
  );
  FDCE #(
    .INIT(1'hx)
  ) _114_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_021_),
    .D(_000_[2]),
    .Q(bitCell_cntrH[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _115_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_022_),
    .D(_000_[3]),
    .Q(bitCell_cntrH[3])
  );
  FDCE #(
    .INIT(1'hx)
  ) _116_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_023_),
    .D(_000_[4]),
    .Q(bitCell_cntrH[4])
  );
  FDCE #(
    .INIT(1'hx)
  ) _117_ (
    .C(sys_clk),
    .CE(_009_),
    .CLR(_024_),
    .D(_002_[0]),
    .Q(xmit_ShiftRegH[0])
  );
  FDCE #(
    .INIT(1'hx)
  ) _118_ (
    .C(sys_clk),
    .CE(_009_),
    .CLR(_025_),
    .D(_002_[1]),
    .Q(xmit_ShiftRegH[1])
  );
  FDCE #(
    .INIT(1'hx)
  ) _119_ (
    .C(sys_clk),
    .CE(_009_),
    .CLR(_026_),
    .D(_002_[2]),
    .Q(xmit_ShiftRegH[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _120_ (
    .C(sys_clk),
    .CE(_009_),
    .CLR(_027_),
    .D(_002_[3]),
    .Q(xmit_ShiftRegH[3])
  );
  FDCE #(
    .INIT(1'hx)
  ) _121_ (
    .C(sys_clk),
    .CE(_009_),
    .CLR(_028_),
    .D(_002_[4]),
    .Q(xmit_ShiftRegH[4])
  );
  FDCE #(
    .INIT(1'hx)
  ) _122_ (
    .C(sys_clk),
    .CE(_009_),
    .CLR(_029_),
    .D(_002_[5]),
    .Q(xmit_ShiftRegH[5])
  );
  FDCE #(
    .INIT(1'hx)
  ) _123_ (
    .C(sys_clk),
    .CE(_009_),
    .CLR(_030_),
    .D(_002_[6]),
    .Q(xmit_ShiftRegH[6])
  );
  FDCE #(
    .INIT(1'hx)
  ) _124_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_031_),
    .D(_040_),
    .Q(xmit_ShiftRegH[7])
  );
  LUT6 #(
    .INIT(64'hf0aabbf0ffaabbee)
  ) _125_ (
    .I0(xmit_ShiftRegH[7]),
    .I1(state[0]),
    .I2(xmit_dataH[7]),
    .I3(state[2]),
    .I4(state[1]),
    .I5(xmitH),
    .O(_040_)
  );
  assign { _042_[5:4], _042_[2] } = { state[2], state[0], state[1] };
  assign _041_[1] = _034_[0];
  assign _043_[1] = _039_[0];
  assign _033_[4:1] = bitCell_cntrH[4:1];
  assign _035_[4:0] = _032_;
  assign _036_[4:0] = _034_;
  assign _038_[3:1] = bitCountH[3:1];
endmodule

module uart(sys_clk, sys_rst_l, uart_clk, uart_XMIT_dataH, xmitH, xmit_dataH, xmit_doneH, uart_REC_dataH, rec_dataH, rec_readyH);
  wire _00_;
  wire _01_;
  wire [7:0] _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire [7:0] _10_;
  wire _11_;
  output [7:0] rec_dataH;
  wire [7:0] rec_dataH;
  output rec_readyH;
  wire rec_readyH;
  input sys_clk;
  wire sys_clk;
  input sys_rst_l;
  wire sys_rst_l;
  input uart_REC_dataH;
  wire uart_REC_dataH;
  output uart_XMIT_dataH;
  wire uart_XMIT_dataH;
  output uart_clk;
  wire uart_clk;
  input xmitH;
  wire xmitH;
  input [7:0] xmit_dataH;
  wire [7:0] xmit_dataH;
  output xmit_doneH;
  wire xmit_doneH;
  BUFG _12_ (
    .I(_00_),
    .O(_04_)
  );
  BUFG _13_ (
    .I(_01_),
    .O(_08_)
  );
  OBUF _14_ (
    .I(_02_[0]),
    .O(rec_dataH[0])
  );
  OBUF _15_ (
    .I(_02_[1]),
    .O(rec_dataH[1])
  );
  OBUF _16_ (
    .I(_02_[2]),
    .O(rec_dataH[2])
  );
  OBUF _17_ (
    .I(_02_[3]),
    .O(rec_dataH[3])
  );
  OBUF _18_ (
    .I(_02_[4]),
    .O(rec_dataH[4])
  );
  OBUF _19_ (
    .I(_02_[5]),
    .O(rec_dataH[5])
  );
  OBUF _20_ (
    .I(_02_[6]),
    .O(rec_dataH[6])
  );
  OBUF _21_ (
    .I(_02_[7]),
    .O(rec_dataH[7])
  );
  OBUF _22_ (
    .I(_03_),
    .O(rec_readyH)
  );
  IBUF _23_ (
    .I(sys_clk),
    .O(_00_)
  );
  IBUF _24_ (
    .I(sys_rst_l),
    .O(_05_)
  );
  IBUF _25_ (
    .I(uart_REC_dataH),
    .O(_06_)
  );
  OBUF _26_ (
    .I(_07_),
    .O(uart_XMIT_dataH)
  );
  OBUF _27_ (
    .I(_08_),
    .O(uart_clk)
  );
  IBUF _28_ (
    .I(xmitH),
    .O(_09_)
  );
  IBUF _29_ (
    .I(xmit_dataH[0]),
    .O(_10_[0])
  );
  IBUF _30_ (
    .I(xmit_dataH[1]),
    .O(_10_[1])
  );
  IBUF _31_ (
    .I(xmit_dataH[2]),
    .O(_10_[2])
  );
  IBUF _32_ (
    .I(xmit_dataH[3]),
    .O(_10_[3])
  );
  IBUF _33_ (
    .I(xmit_dataH[4]),
    .O(_10_[4])
  );
  IBUF _34_ (
    .I(xmit_dataH[5]),
    .O(_10_[5])
  );
  IBUF _35_ (
    .I(xmit_dataH[6]),
    .O(_10_[6])
  );
  IBUF _36_ (
    .I(xmit_dataH[7]),
    .O(_10_[7])
  );
  OBUF _37_ (
    .I(_11_),
    .O(xmit_doneH)
  );
  baud iBAUD (
    .baud_clk(_01_),
    .sys_clk(_04_),
    .sys_rst_l(_05_)
  );
  u_rec iRECEIVER (
    .rec_dataH(_02_),
    .rec_readyH(_03_),
    .sys_clk(_08_),
    .sys_rst_l(_05_),
    .uart_dataH(_06_)
  );
  u_xmit iXMIT (
    .sys_clk(_08_),
    .sys_rst_l(_05_),
    .uart_xmitH(_07_),
    .xmitH(_09_),
    .xmit_dataH(_10_),
    .xmit_doneH(_11_)
  );
endmodule
