/* Generated by Yosys 0.39+147 (git sha1 0a854cf4c, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

module u_rec(sys_rst_l, sys_clk, uart_dataH, rec_dataH, rec_readyH);
  wire [3:0] _000_;
  wire [3:0] _001_;
  wire [6:0] _002_;
  wire _003_;
  wire _004_;
  wire [6:0] _005_;
  wire _006_;
  wire _007_;
  wire [6:0] _008_;
  wire _009_;
  wire _010_;
  wire [6:0] _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire [3:0] _042_;
  wire [3:0] _043_;
  wire [3:0] _044_;
  wire [3:0] _045_;
  wire [3:0] _046_;
  wire [1:0] _047_;
  wire [4:0] _048_;
  wire [5:0] _049_;
  wire [3:0] bitCell_cntrH;
  wire ena;
  wire [2:0] next_state;
  wire [7:0] par_dataH;
  wire rec_datH;
  wire rec_datSyncH;
  output [7:0] rec_dataH;
  wire [7:0] rec_dataH;
  wire rec_data_cntrH_1;
  wire rec_data_cntrH_2;
  output rec_readyH;
  wire rec_readyH;
  wire rec_readyH_temp;
  wire rec_readyInH;
  wire [3:0] recd_bitCntrH;
  wire [2:0] state;
  input sys_clk;
  wire sys_clk;
  input sys_rst_l;
  wire sys_rst_l;
  input uart_dataH;
  wire uart_dataH;
  LUT3 #(
    .INIT(8'hc5)
  ) _050_ (
    .I0(state[0]),
    .I1(state[2]),
    .I2(state[1]),
    .O(_047_[0])
  );
  LUT4 #(
    .INIT(16'hf03b)
  ) _051_ (
    .I0(rec_datH),
    .I1(state[0]),
    .I2(state[2]),
    .I3(state[1]),
    .O(_015_)
  );
  LUT4 #(
    .INIT(16'hbfff)
  ) _052_ (
    .I0(state[2]),
    .I1(_048_[1]),
    .I2(_049_[2]),
    .I3(rec_datH),
    .O(_016_)
  );
  LUT2 #(
    .INIT(4'h4)
  ) _053_ (
    .I0(state[0]),
    .I1(state[1]),
    .O(_049_[2])
  );
  LUT4 #(
    .INIT(16'h0100)
  ) _054_ (
    .I0(bitCell_cntrH[0]),
    .I1(bitCell_cntrH[1]),
    .I2(bitCell_cntrH[3]),
    .I3(bitCell_cntrH[2]),
    .O(_048_[1])
  );
  LUT5 #(
    .INIT(32'd3221225471)
  ) _055_ (
    .I0(state[2]),
    .I1(_048_[1]),
    .I2(_049_[2]),
    .I3(rec_datH),
    .I4(rec_data_cntrH_1),
    .O(_017_)
  );
  LUT6 #(
    .INIT(64'h1000000000000000)
  ) _056_ (
    .I0(state[2]),
    .I1(ena),
    .I2(_049_[2]),
    .I3(_048_[1]),
    .I4(rec_datH),
    .I5(rec_data_cntrH_2),
    .O(_041_)
  );
  LUT2 #(
    .INIT(4'h4)
  ) _057_ (
    .I0(ena),
    .I1(par_dataH[0]),
    .O(rec_dataH[0])
  );
  LUT2 #(
    .INIT(4'h4)
  ) _058_ (
    .I0(ena),
    .I1(par_dataH[1]),
    .O(rec_dataH[1])
  );
  LUT2 #(
    .INIT(4'h4)
  ) _059_ (
    .I0(ena),
    .I1(par_dataH[2]),
    .O(rec_dataH[2])
  );
  LUT2 #(
    .INIT(4'h4)
  ) _060_ (
    .I0(ena),
    .I1(par_dataH[3]),
    .O(rec_dataH[3])
  );
  LUT2 #(
    .INIT(4'h4)
  ) _061_ (
    .I0(ena),
    .I1(par_dataH[4]),
    .O(rec_dataH[4])
  );
  LUT2 #(
    .INIT(4'h4)
  ) _062_ (
    .I0(ena),
    .I1(par_dataH[5]),
    .O(rec_dataH[5])
  );
  LUT2 #(
    .INIT(4'h4)
  ) _063_ (
    .I0(ena),
    .I1(par_dataH[6]),
    .O(rec_dataH[6])
  );
  LUT2 #(
    .INIT(4'h4)
  ) _064_ (
    .I0(ena),
    .I1(par_dataH[7]),
    .O(rec_dataH[7])
  );
  LUT2 #(
    .INIT(4'h4)
  ) _065_ (
    .I0(ena),
    .I1(rec_readyH_temp),
    .O(rec_readyH)
  );
  LUT2 #(
    .INIT(4'h8)
  ) _066_ (
    .I0(_047_[0]),
    .I1(_046_[0]),
    .O(_001_[0])
  );
  LUT2 #(
    .INIT(4'h8)
  ) _067_ (
    .I0(_047_[0]),
    .I1(_046_[1]),
    .O(_001_[1])
  );
  LUT2 #(
    .INIT(4'h8)
  ) _068_ (
    .I0(_047_[0]),
    .I1(_046_[2]),
    .O(_001_[2])
  );
  LUT2 #(
    .INIT(4'h8)
  ) _069_ (
    .I0(_047_[0]),
    .I1(_046_[3]),
    .O(_001_[3])
  );
  LUT4 #(
    .INIT(16'h888a)
  ) _070_ (
    .I0(_002_[0]),
    .I1(state[1]),
    .I2(state[2]),
    .I3(state[0]),
    .O(_003_)
  );
  LUT6 #(
    .INIT(64'h808a888a888a0800)
  ) _071_ (
    .I0(_002_[0]),
    .I1(state[1]),
    .I2(state[2]),
    .I3(state[0]),
    .I4(bitCell_cntrH[3]),
    .I5(bitCell_cntrH[1]),
    .O(_004_)
  );
  MUXF7 _072_ (
    .I0(_003_),
    .I1(_004_),
    .O(_000_[0]),
    .S(_002_[6])
  );
  LUT2 #(
    .INIT(4'h4)
  ) _073_ (
    .I0(bitCell_cntrH[0]),
    .I1(bitCell_cntrH[2]),
    .O(_002_[6])
  );
  LUT4 #(
    .INIT(16'h888a)
  ) _074_ (
    .I0(_005_[0]),
    .I1(state[1]),
    .I2(state[2]),
    .I3(state[0]),
    .O(_006_)
  );
  LUT6 #(
    .INIT(64'h808a888a888a0800)
  ) _075_ (
    .I0(_005_[0]),
    .I1(state[1]),
    .I2(state[2]),
    .I3(state[0]),
    .I4(bitCell_cntrH[3]),
    .I5(bitCell_cntrH[1]),
    .O(_007_)
  );
  MUXF7 _076_ (
    .I0(_006_),
    .I1(_007_),
    .O(_000_[1]),
    .S(_002_[6])
  );
  LUT4 #(
    .INIT(16'h888a)
  ) _077_ (
    .I0(_008_[0]),
    .I1(state[1]),
    .I2(state[2]),
    .I3(state[0]),
    .O(_009_)
  );
  LUT6 #(
    .INIT(64'h808a888a888a0800)
  ) _078_ (
    .I0(_008_[0]),
    .I1(state[1]),
    .I2(state[2]),
    .I3(state[0]),
    .I4(bitCell_cntrH[3]),
    .I5(bitCell_cntrH[1]),
    .O(_010_)
  );
  MUXF7 _079_ (
    .I0(_009_),
    .I1(_010_),
    .O(_000_[2]),
    .S(_002_[6])
  );
  LUT4 #(
    .INIT(16'h888a)
  ) _080_ (
    .I0(_011_[0]),
    .I1(state[1]),
    .I2(state[2]),
    .I3(state[0]),
    .O(_012_)
  );
  LUT6 #(
    .INIT(64'h808a888a888a0800)
  ) _081_ (
    .I0(_011_[0]),
    .I1(state[1]),
    .I2(state[2]),
    .I3(state[0]),
    .I4(bitCell_cntrH[3]),
    .I5(bitCell_cntrH[1]),
    .O(_013_)
  );
  MUXF7 _082_ (
    .I0(_012_),
    .I1(_013_),
    .O(_000_[3]),
    .S(_002_[6])
  );
  LUT4 #(
    .INIT(16'hca0c)
  ) _083_ (
    .I0(state[0]),
    .I1(rec_datH),
    .I2(state[1]),
    .I3(state[2]),
    .O(rec_readyInH)
  );
  LUT5 #(
    .INIT(32'd4244307967)
  ) _084_ (
    .I0(rec_datH),
    .I1(_048_[1]),
    .I2(_048_[2]),
    .I3(state[1]),
    .I4(_048_[4]),
    .O(next_state[0])
  );
  LUT6 #(
    .INIT(64'h4000ffffffffffff)
  ) _085_ (
    .I0(bitCell_cntrH[0]),
    .I1(bitCell_cntrH[1]),
    .I2(bitCell_cntrH[3]),
    .I3(bitCell_cntrH[2]),
    .I4(state[0]),
    .I5(state[1]),
    .O(_014_)
  );
  MUXF7 _086_ (
    .I0(_014_),
    .I1(1'h0),
    .O(_048_[4]),
    .S(state[2])
  );
  LUT6 #(
    .INIT(64'h0100000000000000)
  ) _087_ (
    .I0(recd_bitCntrH[0]),
    .I1(recd_bitCntrH[1]),
    .I2(recd_bitCntrH[2]),
    .I3(state[1]),
    .I4(recd_bitCntrH[3]),
    .I5(state[0]),
    .O(_048_[2])
  );
  LUT6 #(
    .INIT(64'h05000f3f3f3f3f3f)
  ) _088_ (
    .I0(_048_[1]),
    .I1(state[2]),
    .I2(state[0]),
    .I3(state[1]),
    .I4(rec_datH),
    .I5(_048_[4]),
    .O(next_state[1])
  );
  LUT6 #(
    .INIT(64'h4000000000000000)
  ) _089_ (
    .I0(state[2]),
    .I1(state[1]),
    .I2(_002_[6]),
    .I3(bitCell_cntrH[1]),
    .I4(bitCell_cntrH[3]),
    .I5(state[0]),
    .O(next_state[2])
  );
  INV _090_ (
    .I(sys_rst_l),
    .O(_019_)
  );
  INV _091_ (
    .I(recd_bitCntrH[0]),
    .O(_045_[0])
  );
  LUT6 #(
    .INIT(64'hefffffffffffffff)
  ) _092_ (
    .I0(state[2]),
    .I1(ena),
    .I2(_049_[2]),
    .I3(_048_[1]),
    .I4(rec_datH),
    .I5(rec_data_cntrH_2),
    .O(_018_)
  );
  INV _093_ (
    .I(bitCell_cntrH[0]),
    .O(_043_[0])
  );
  INV _094_ (
    .I(sys_rst_l),
    .O(_020_)
  );
  INV _095_ (
    .I(sys_rst_l),
    .O(_021_)
  );
  INV _096_ (
    .I(sys_rst_l),
    .O(_022_)
  );
  INV _097_ (
    .I(sys_rst_l),
    .O(_023_)
  );
  INV _098_ (
    .I(sys_rst_l),
    .O(_024_)
  );
  INV _099_ (
    .I(sys_rst_l),
    .O(_025_)
  );
  INV _100_ (
    .I(sys_rst_l),
    .O(_026_)
  );
  INV _101_ (
    .I(sys_rst_l),
    .O(_027_)
  );
  INV _102_ (
    .I(sys_rst_l),
    .O(_028_)
  );
  INV _103_ (
    .I(sys_rst_l),
    .O(_029_)
  );
  INV _104_ (
    .I(sys_rst_l),
    .O(_030_)
  );
  INV _105_ (
    .I(sys_rst_l),
    .O(_031_)
  );
  INV _106_ (
    .I(sys_rst_l),
    .O(_032_)
  );
  INV _107_ (
    .I(sys_rst_l),
    .O(_033_)
  );
  INV _108_ (
    .I(sys_rst_l),
    .O(_034_)
  );
  INV _109_ (
    .I(sys_rst_l),
    .O(_035_)
  );
  INV _110_ (
    .I(sys_rst_l),
    .O(_036_)
  );
  INV _111_ (
    .I(sys_rst_l),
    .O(_037_)
  );
  INV _112_ (
    .I(sys_rst_l),
    .O(_038_)
  );
  INV _113_ (
    .I(sys_rst_l),
    .O(_039_)
  );
  INV _114_ (
    .I(sys_rst_l),
    .O(_040_)
  );
  CARRY4 _115_ (
    .CI(1'h0),
    .CO(_042_),
    .CYINIT(1'h0),
    .DI(4'h1),
    .O({ _011_[0], _008_[0], _005_[0], _002_[0] }),
    .S({ bitCell_cntrH[3:1], _043_[0] })
  );
  CARRY4 _116_ (
    .CI(1'h0),
    .CO(_044_),
    .CYINIT(1'h0),
    .DI(4'h1),
    .O(_046_),
    .S({ recd_bitCntrH[3:1], _045_[0] })
  );
  FDCE #(
    .INIT(1'hx)
  ) _117_ (
    .C(sys_clk),
    .CE(_047_[0]),
    .CLR(_019_),
    .D(par_dataH[1]),
    .Q(par_dataH[0])
  );
  FDCE #(
    .INIT(1'hx)
  ) _118_ (
    .C(sys_clk),
    .CE(_047_[0]),
    .CLR(_020_),
    .D(par_dataH[2]),
    .Q(par_dataH[1])
  );
  FDCE #(
    .INIT(1'hx)
  ) _119_ (
    .C(sys_clk),
    .CE(_047_[0]),
    .CLR(_021_),
    .D(par_dataH[3]),
    .Q(par_dataH[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _120_ (
    .C(sys_clk),
    .CE(_047_[0]),
    .CLR(_022_),
    .D(par_dataH[4]),
    .Q(par_dataH[3])
  );
  FDCE #(
    .INIT(1'hx)
  ) _121_ (
    .C(sys_clk),
    .CE(_047_[0]),
    .CLR(_023_),
    .D(par_dataH[5]),
    .Q(par_dataH[4])
  );
  FDCE #(
    .INIT(1'hx)
  ) _122_ (
    .C(sys_clk),
    .CE(_047_[0]),
    .CLR(_024_),
    .D(par_dataH[6]),
    .Q(par_dataH[5])
  );
  FDCE #(
    .INIT(1'hx)
  ) _123_ (
    .C(sys_clk),
    .CE(_047_[0]),
    .CLR(_025_),
    .D(par_dataH[7]),
    .Q(par_dataH[6])
  );
  FDCE #(
    .INIT(1'hx)
  ) _124_ (
    .C(sys_clk),
    .CE(_047_[0]),
    .CLR(_026_),
    .D(rec_datH),
    .Q(par_dataH[7])
  );
  LDCE #(
    .INIT(1'h0),
    .IS_G_INVERTED(1'h1)
  ) _125_ (
    .CLR(1'h0),
    .D(1'h1),
    .G(_016_),
    .GE(1'h1),
    .Q(rec_data_cntrH_1)
  );
  LDCE #(
    .INIT(1'h0),
    .IS_G_INVERTED(1'h1)
  ) _126_ (
    .CLR(1'h0),
    .D(1'h1),
    .G(_017_),
    .GE(1'h1),
    .Q(rec_data_cntrH_2)
  );
  LDCE #(
    .INIT(1'h0),
    .IS_G_INVERTED(1'h1)
  ) _127_ (
    .CLR(1'h0),
    .D(1'h1),
    .G(_018_),
    .GE(1'h1),
    .Q(ena)
  );
  FDCE #(
    .INIT(1'hx)
  ) _128_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_027_),
    .D(rec_readyInH),
    .Q(rec_readyH_temp)
  );
  FDPE #(
    .INIT(1'hx)
  ) _129_ (
    .C(sys_clk),
    .CE(1'h1),
    .D(next_state[0]),
    .PRE(_028_),
    .Q(state[0])
  );
  FDCE #(
    .INIT(1'hx)
  ) _130_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_029_),
    .D(next_state[1]),
    .Q(state[1])
  );
  FDCE #(
    .INIT(1'hx)
  ) _131_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_030_),
    .D(next_state[2]),
    .Q(state[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _132_ (
    .C(sys_clk),
    .CE(_015_),
    .CLR(_031_),
    .D(_001_[0]),
    .Q(recd_bitCntrH[0])
  );
  FDCE #(
    .INIT(1'hx)
  ) _133_ (
    .C(sys_clk),
    .CE(_015_),
    .CLR(_032_),
    .D(_001_[1]),
    .Q(recd_bitCntrH[1])
  );
  FDCE #(
    .INIT(1'hx)
  ) _134_ (
    .C(sys_clk),
    .CE(_015_),
    .CLR(_033_),
    .D(_001_[2]),
    .Q(recd_bitCntrH[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _135_ (
    .C(sys_clk),
    .CE(_015_),
    .CLR(_034_),
    .D(_001_[3]),
    .Q(recd_bitCntrH[3])
  );
  FDCE #(
    .INIT(1'hx)
  ) _136_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_035_),
    .D(_000_[0]),
    .Q(bitCell_cntrH[0])
  );
  FDCE #(
    .INIT(1'hx)
  ) _137_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_036_),
    .D(_000_[1]),
    .Q(bitCell_cntrH[1])
  );
  FDCE #(
    .INIT(1'hx)
  ) _138_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_037_),
    .D(_000_[2]),
    .Q(bitCell_cntrH[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _139_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_038_),
    .D(_000_[3]),
    .Q(bitCell_cntrH[3])
  );
  FDPE #(
    .INIT(1'hx)
  ) _140_ (
    .C(sys_clk),
    .CE(1'h1),
    .D(rec_datSyncH),
    .PRE(_039_),
    .Q(rec_datH)
  );
  FDPE #(
    .INIT(1'hx)
  ) _141_ (
    .C(sys_clk),
    .CE(1'h1),
    .D(uart_dataH),
    .PRE(_040_),
    .Q(rec_datSyncH)
  );
  always @*
    if (_041_)
      $write("Trojan Activated\n");
  assign _002_[5:1] = { bitCell_cntrH[1], bitCell_cntrH[3], state[0], state[2:1] };
  assign _005_[6:1] = { _002_[6], bitCell_cntrH[1], bitCell_cntrH[3], state[0], state[2:1] };
  assign _008_[6:1] = { _002_[6], bitCell_cntrH[1], bitCell_cntrH[3], state[0], state[2:1] };
  assign _011_[6:1] = { _002_[6], bitCell_cntrH[1], bitCell_cntrH[3], state[0], state[2:1] };
  assign _043_[3:1] = bitCell_cntrH[3:1];
  assign _045_[3:1] = recd_bitCntrH[3:1];
  assign _047_[1] = _046_[2];
  assign { _048_[3], _048_[0] } = { state[1], rec_datH };
  assign { _049_[5:3], _049_[1:0] } = { rec_data_cntrH_2, rec_datH, _048_[1], ena, state[2] };
endmodule

module u_xmit(sys_clk, sys_rst_l, uart_xmitH, xmitH, xmit_dataH, xmit_doneH);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire [3:0] bitCell_cntrH;
  wire [3:0] bitCountH;
  wire [2:0] next_state;
  wire [2:0] state;
  input sys_clk;
  wire sys_clk;
  input sys_rst_l;
  wire sys_rst_l;
  output uart_xmitH;
  wire uart_xmitH;
  input xmitH;
  wire xmitH;
  wire [7:0] xmit_ShiftRegH;
  input [7:0] xmit_dataH;
  wire [7:0] xmit_dataH;
  output xmit_doneH;
  wire xmit_doneH;
  wire xmit_doneInH;
  LUT3 #(
    .INIT(8'h41)
  ) _04_ (
    .I0(xmitH),
    .I1(state[2]),
    .I2(state[1]),
    .O(xmit_doneInH)
  );
  LUT3 #(
    .INIT(8'hf8)
  ) _05_ (
    .I0(state[1]),
    .I1(state[0]),
    .I2(state[2]),
    .O(next_state[0])
  );
  LUT4 #(
    .INIT(16'h05fc)
  ) _06_ (
    .I0(state[0]),
    .I1(xmitH),
    .I2(state[1]),
    .I3(state[2]),
    .O(next_state[1])
  );
  LUT3 #(
    .INIT(8'he0)
  ) _07_ (
    .I0(state[1]),
    .I1(state[0]),
    .I2(state[2]),
    .O(next_state[2])
  );
  LUT3 #(
    .INIT(8'h41)
  ) _08_ (
    .I0(state[1]),
    .I1(state[0]),
    .I2(state[2]),
    .O(uart_xmitH)
  );
  INV _09_ (
    .I(sys_rst_l),
    .O(_00_)
  );
  INV _10_ (
    .I(sys_rst_l),
    .O(_02_)
  );
  INV _11_ (
    .I(sys_rst_l),
    .O(_01_)
  );
  INV _12_ (
    .I(sys_rst_l),
    .O(_03_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _13_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_00_),
    .D(xmit_doneInH),
    .Q(xmit_doneH)
  );
  FDCE #(
    .INIT(1'hx)
  ) _14_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_01_),
    .D(next_state[0]),
    .Q(state[0])
  );
  FDCE #(
    .INIT(1'hx)
  ) _15_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_02_),
    .D(next_state[1]),
    .Q(state[1])
  );
  FDCE #(
    .INIT(1'hx)
  ) _16_ (
    .C(sys_clk),
    .CE(1'h1),
    .CLR(_03_),
    .D(next_state[2]),
    .Q(state[2])
  );
  assign bitCell_cntrH = 4'h0;
  assign bitCountH = 4'h0;
  assign xmit_ShiftRegH = 8'h00;
endmodule

module uart(sys_clk, sys_rst_l, uart_XMIT_dataH, xmitH, xmit_dataH, xmit_doneH, uart_REC_dataH, rec_dataH, rec_readyH);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire [7:0] _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire [7:0] _24_;
  wire _25_;
  wire _26_;
  output [7:0] rec_dataH;
  wire [7:0] rec_dataH;
  wire [7:0] rec_dataH_rec;
  wire [7:0] rec_dataH_temp;
  output rec_readyH;
  wire rec_readyH;
  input sys_clk;
  wire sys_clk;
  input sys_rst_l;
  wire sys_rst_l;
  input uart_REC_dataH;
  wire uart_REC_dataH;
  output uart_XMIT_dataH;
  wire uart_XMIT_dataH;
  input xmitH;
  wire xmitH;
  input [7:0] xmit_dataH;
  wire [7:0] xmit_dataH;
  output xmit_doneH;
  wire xmit_doneH;
  INV _27_ (
    .I(_26_),
    .O(_00_)
  );
  INV _28_ (
    .I(_26_),
    .O(_01_)
  );
  INV _29_ (
    .I(_26_),
    .O(_02_)
  );
  INV _30_ (
    .I(_26_),
    .O(_03_)
  );
  INV _31_ (
    .I(_26_),
    .O(_04_)
  );
  INV _32_ (
    .I(_26_),
    .O(_05_)
  );
  INV _33_ (
    .I(_26_),
    .O(_06_)
  );
  INV _34_ (
    .I(_26_),
    .O(_07_)
  );
  INV _35_ (
    .I(_26_),
    .O(_08_)
  );
  INV _36_ (
    .I(_26_),
    .O(_09_)
  );
  INV _37_ (
    .I(_26_),
    .O(_10_)
  );
  INV _38_ (
    .I(_26_),
    .O(_11_)
  );
  INV _39_ (
    .I(_26_),
    .O(_12_)
  );
  INV _40_ (
    .I(_26_),
    .O(_13_)
  );
  INV _41_ (
    .I(_26_),
    .O(_14_)
  );
  INV _42_ (
    .I(_26_),
    .O(_15_)
  );
  BUFG _43_ (
    .I(_16_),
    .O(_19_)
  );
  BUFG _44_ (
    .I(_17_),
    .O(_20_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _45_ (
    .C(_19_),
    .CE(1'h1),
    .CLR(_00_),
    .D(rec_dataH_rec[0]),
    .Q(rec_dataH_temp[0])
  );
  FDCE #(
    .INIT(1'hx)
  ) _46_ (
    .C(_19_),
    .CE(1'h1),
    .CLR(_01_),
    .D(rec_dataH_rec[1]),
    .Q(rec_dataH_temp[1])
  );
  FDCE #(
    .INIT(1'hx)
  ) _47_ (
    .C(_19_),
    .CE(1'h1),
    .CLR(_02_),
    .D(rec_dataH_rec[2]),
    .Q(rec_dataH_temp[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _48_ (
    .C(_19_),
    .CE(1'h1),
    .CLR(_03_),
    .D(rec_dataH_rec[3]),
    .Q(rec_dataH_temp[3])
  );
  FDCE #(
    .INIT(1'hx)
  ) _49_ (
    .C(_19_),
    .CE(1'h1),
    .CLR(_04_),
    .D(rec_dataH_rec[4]),
    .Q(rec_dataH_temp[4])
  );
  FDCE #(
    .INIT(1'hx)
  ) _50_ (
    .C(_19_),
    .CE(1'h1),
    .CLR(_05_),
    .D(rec_dataH_rec[5]),
    .Q(rec_dataH_temp[5])
  );
  FDCE #(
    .INIT(1'hx)
  ) _51_ (
    .C(_19_),
    .CE(1'h1),
    .CLR(_06_),
    .D(rec_dataH_rec[6]),
    .Q(rec_dataH_temp[6])
  );
  FDCE #(
    .INIT(1'hx)
  ) _52_ (
    .C(_19_),
    .CE(1'h1),
    .CLR(_07_),
    .D(rec_dataH_rec[7]),
    .Q(rec_dataH_temp[7])
  );
  FDCE #(
    .INIT(1'hx)
  ) _53_ (
    .C(_20_),
    .CE(1'h1),
    .CLR(_08_),
    .D(rec_dataH_temp[0]),
    .Q(_18_[0])
  );
  FDCE #(
    .INIT(1'hx)
  ) _54_ (
    .C(_20_),
    .CE(1'h1),
    .CLR(_09_),
    .D(rec_dataH_temp[1]),
    .Q(_18_[1])
  );
  FDCE #(
    .INIT(1'hx)
  ) _55_ (
    .C(_20_),
    .CE(1'h1),
    .CLR(_10_),
    .D(rec_dataH_temp[2]),
    .Q(_18_[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _56_ (
    .C(_20_),
    .CE(1'h1),
    .CLR(_11_),
    .D(rec_dataH_temp[3]),
    .Q(_18_[3])
  );
  FDCE #(
    .INIT(1'hx)
  ) _57_ (
    .C(_20_),
    .CE(1'h1),
    .CLR(_12_),
    .D(rec_dataH_temp[4]),
    .Q(_18_[4])
  );
  FDCE #(
    .INIT(1'hx)
  ) _58_ (
    .C(_20_),
    .CE(1'h1),
    .CLR(_13_),
    .D(rec_dataH_temp[5]),
    .Q(_18_[5])
  );
  FDCE #(
    .INIT(1'hx)
  ) _59_ (
    .C(_20_),
    .CE(1'h1),
    .CLR(_14_),
    .D(rec_dataH_temp[6]),
    .Q(_18_[6])
  );
  FDCE #(
    .INIT(1'hx)
  ) _60_ (
    .C(_20_),
    .CE(1'h1),
    .CLR(_15_),
    .D(rec_dataH_temp[7]),
    .Q(_18_[7])
  );
  OBUF _61_ (
    .I(_18_[0]),
    .O(rec_dataH[0])
  );
  OBUF _62_ (
    .I(_18_[1]),
    .O(rec_dataH[1])
  );
  OBUF _63_ (
    .I(_18_[2]),
    .O(rec_dataH[2])
  );
  OBUF _64_ (
    .I(_18_[3]),
    .O(rec_dataH[3])
  );
  OBUF _65_ (
    .I(_18_[4]),
    .O(rec_dataH[4])
  );
  OBUF _66_ (
    .I(_18_[5]),
    .O(rec_dataH[5])
  );
  OBUF _67_ (
    .I(_18_[6]),
    .O(rec_dataH[6])
  );
  OBUF _68_ (
    .I(_18_[7]),
    .O(rec_dataH[7])
  );
  OBUF _69_ (
    .I(_19_),
    .O(rec_readyH)
  );
  IBUF _70_ (
    .I(sys_clk),
    .O(_17_)
  );
  IBUF _71_ (
    .I(sys_rst_l),
    .O(_26_)
  );
  IBUF _72_ (
    .I(uart_REC_dataH),
    .O(_21_)
  );
  OBUF _73_ (
    .I(_22_),
    .O(uart_XMIT_dataH)
  );
  IBUF _74_ (
    .I(xmitH),
    .O(_23_)
  );
  IBUF _75_ (
    .I(xmit_dataH[0]),
    .O(_24_[0])
  );
  IBUF _76_ (
    .I(xmit_dataH[1]),
    .O(_24_[1])
  );
  IBUF _77_ (
    .I(xmit_dataH[2]),
    .O(_24_[2])
  );
  IBUF _78_ (
    .I(xmit_dataH[3]),
    .O(_24_[3])
  );
  IBUF _79_ (
    .I(xmit_dataH[4]),
    .O(_24_[4])
  );
  IBUF _80_ (
    .I(xmit_dataH[5]),
    .O(_24_[5])
  );
  IBUF _81_ (
    .I(xmit_dataH[6]),
    .O(_24_[6])
  );
  IBUF _82_ (
    .I(xmit_dataH[7]),
    .O(_24_[7])
  );
  OBUF _83_ (
    .I(_25_),
    .O(xmit_doneH)
  );
  u_rec iRECEIVER (
    .rec_dataH(rec_dataH_rec),
    .rec_readyH(_16_),
    .sys_clk(_20_),
    .sys_rst_l(_26_),
    .uart_dataH(_21_)
  );
  u_xmit iXMIT (
    .sys_clk(_20_),
    .sys_rst_l(_26_),
    .uart_xmitH(_22_),
    .xmitH(_23_),
    .xmit_dataH(_24_),
    .xmit_doneH(_25_)
  );
endmodule
